import useRequestCenter from "../axios/useAxiosRequests";

export const useAxiosProvider = {
    getRequestDetail: useRequestCenter('Request/Get', 'GET'),
    getWaitingSpecialUsers: useRequestCenter('User/GetWaitingSpecialUser', 'GET'),
    updateTestQuestion: useRequestCenter('Test/UpdateTestQuestion', 'POST'),
    getRandomQuestions: useRequestCenter('Test/GetRandomQuestions', 'GET'),
    confirmRequestByCustomer: useRequestCenter('Request/Confirm', 'POST'),
    setFinalConfirmation: useRequestCenter('Request/SetFinalConfirmation', 'POST'),
    setRequestRate: useRequestCenter('Request/SetRate', 'POST'),
    createRequestComplaint: useRequestCenter('Request/CreateRequestComplaint', 'POST'),
    updatePersonnel: useRequestCenter('User/UpdateUserByCustomerAdmin', 'POST'),
    removePersonnel: useRequestCenter('Company/RemoveFromCompany', 'POST'),
    getCompanyAddress: useRequestCenter('Company/GetAllCompanyAddress', 'GET'),
    getCompanyAddressForAdmin: useRequestCenter('Company/GetAllCompanyAddressByUserId', 'GET'),
    getRequestComplaints: useRequestCenter('Request/GetAllComplaints', 'GET'),
    getCompanyComplaints: useRequestCenter('Request/GetCompanyComplaintsByCompanyId', 'GET'),
    getRequestComplaint: useRequestCenter('Request/GetRequestComplaint', 'GET'),
    getUserById: useRequestCenter('User/Get'),
    getRegistertionErrors: useRequestCenter('User/GetRegistrationError', "GET"),
    getUserBankAccounts: useRequestCenter('User/GetBankAccountByUserId', "GET"),
    createAdminPayment: useRequestCenter('Payment/CreateAdminPayment', "POST"),
    setSpecialTypeId: useRequestCenter('User/SetSpecialType', 'POST'),
    answerTest: useRequestCenter('Test/AnswerTestQuestions', 'POST'),
    uploadResume: useRequestCenter('User/UploadResume', 'POST'),
    getInterviewTimes: useRequestCenter('Interview/GetAllInterviewTime', 'GET'),
    createInterview: useRequestCenter('Interview/Create', 'POST'),
    changeRequestComplaintStatus: useRequestCenter('Request/ChangeRequestComplaintStatus', 'POST'),
    setRequestComplaintResult: useRequestCenter('Request/SetRequestComplaintResult', 'POST'),
    setInterviewAsDone: useRequestCenter('Interview/SetInterviewAsDone', 'POST'),
    sendMessage: useRequestCenter('Message/SendMessage', 'POST'),
    getAllCompanyRequests: useRequestCenter('Request/GetAllCompanyRequest', 'GET'),
    getAllRequests: useRequestCenter('Request/GetAll', 'GET'),
    getCompanyPersonnel: useRequestCenter('Company/GetAllCompanyPersonnel', 'GET'),
    getCompanyPersonnelForAdmin: useRequestCenter('Company/GetAllCompanyPersonnelByUserId', 'GET'),
    getBankAccountInfo: useRequestCenter('User/GetMyBankAccounts', 'GET'),
    getExcelPayment: useRequestCenter('Payment/GetPaymentReportAsExcel', 'GET'),
    createBankAccount: useRequestCenter('User/CreateBankAccount', 'POST'),
    updateBankAccount: useRequestCenter('User/UpdateBankAccount', 'POST'),
    getInterviewDetail: useRequestCenter('Interview/GetInterviewDetail', 'GET'),
    getAllPaymentsForCustomerAdmin: useRequestCenter('Payment/GetAllForCustomerAdmin', 'GET'),
    getCompanyFactor: useRequestCenter('Company/GetCompanyFactor', 'GET'),
    getAllPaymentsForSpecialist: useRequestCenter('Payment/GetMyFinancialTurnover', 'GET'),
    createPayment: useRequestCenter('Payment/SendPaymentRequest', 'POST'),
    getInterviewedSpecialists: useRequestCenter('User/GetInterviewedSpecialUser', 'GET'),
    getMyIntroducerCode: useRequestCenter('Marketer/GetIntroducerCode', 'GET'),
    changeRequestServiceType: useRequestCenter('Request/ChangeRequestServiceType', 'POST'),
    createChangeRequestServiceType: useRequestCenter('Request/CreateChangeRequestServiceType', 'POST'),
    createRequestEquipment: useRequestCenter('Request/CreateRequestEquipment', 'POST'),
    getCompanyStatistics: useRequestCenter('Request/GetCompanyRequestStatistics', 'GET'),
    getSpecialStatistics: useRequestCenter('Request/GetSpecialRequestStatistics', 'GET'),
    isResumeUploaded: useRequestCenter('User/IsResumeUpload', 'POST'),
    isSpecialistConfirmed: useRequestCenter('User/CheckSpecialUserConfirmed', 'POST'),
    getSpecialistSummaryTurnover: useRequestCenter('Payment/GetMySummaryFinancialTurnover', 'GET'),
    confirmRequest: useRequestCenter('Requester/Confirm', 'POST'),
    getMyOpenRequest: useRequestCenter('Request/GetMyOpenRequest', 'GET'),
    getAllSpecialists: useRequestCenter('User/GetInterviewedSpecialUser', 'GET'),
    getCompanyCredit: useRequestCenter('Company/GetAvailableCredit', 'POST'),
    getAllSiteConfig: useRequestCenter('SiteConfig/GetAll', 'GET'),
    updateSiteConfig: useRequestCenter('SiteConfig/Update', 'POST'),
    changeInterviewTime: useRequestCenter('Interview/ChangeTime', 'POST'),
    uploadCompanyLogo: useRequestCenter('Company/UploadCompanyLogo', 'POST'),
    verifyPayment: useRequestCenter('Payment/CallBack', 'GET'),
    indexData: useRequestCenter('User/GetIndexData', 'GET'),
    verifyPaymentRequest: useRequestCenter('Payment/VerifyPaymentRequest', 'POST'),
    uploadCompanyLogoByAdmin: useRequestCenter('Company/UploadCompanyLogoByAdmin', 'POST'),
    confirmSpecialist: useRequestCenter('User/ConfirmSpecialUser', 'POST'),
    rejectSpecialist: useRequestCenter('User/RejectSpecialUser', 'POST'),
    createRequest: useRequestCenter('Request/Create', 'POST'),
    getRequestsForSpecialist: useRequestCenter('Request/GetRequestsForSpecialist', 'GET'),
    getRequestsForSupervisor: useRequestCenter('Request/GetRequestsForSupervisor', 'GET'),
    getMyCustomers: useRequestCenter('Marketer/GetMyIntroducedCustomers', 'GET'),
    checkResume: useRequestCenter('User/CheckResume', 'POST'),
    changeUserStatus: useRequestCenter('User/ChangeUserStatus', 'POST'),
    getStaffStatistics: useRequestCenter('Request/GetStaffRequestStatistics', 'GET'),
    getCustomerDetail: useRequestCenter('Marketer/GetCustomerDetail', 'GET'),
    getAllUsers: useRequestCenter('User/GetAll', 'POST'),
    setRequestAsComplete: useRequestCenter('Request/SetRequestAsComplate', 'POST'),
    getUserCompanyForAdmin: useRequestCenter('User/GetUserCompanyByUserId', 'GET'),
    rejectRequestEquipmentItems: useRequestCenter('Request/RejectRequestEquipmentItems', 'POST'),
    confirmRequestEquipmentItems: useRequestCenter('Request/ConfirmRequestEquipmentItems', 'POST'),
    rejectRequestEquipmentItemsPrices: useRequestCenter('Request/RejectRequestEquipmentItemPrices', 'POST'),
    confirmRequestEquipmentItemsPrices: useRequestCenter('Request/ConfirmRequestEquipmentItemPrices', 'POST'),
    rejectChangeRequestServiceType: useRequestCenter('Request/RejectChangeServiceTypeRequest', 'POST'),
    getSupervisorStatistics: useRequestCenter('Request/GetSupervisorRequestStatistics', 'GET'),
    getAllAdminPayments: useRequestCenter('Payment/GetAllAdminPayment', 'GET'),
    getSpecialistsDemands:useRequestCenter('Payment/GetSpecialUserDemands','GET'),
    getMarketerDemands:useRequestCenter('Payment/GetMarketerDemands','GET'),
    acceptToDoLocale:useRequestCenter('Requester/AcceptToDoLocal','POST'),
    rejectToDoLocale:useRequestCenter('Requester/RejectToDoLocal','POST'),


}
