import useRequestCenter from "../composables/useRequests";

export const useApi = {
    signIn: useRequestCenter('Account/SignIn'),
    getLatestProducts: useRequestCenter('https://api.liproj.com/api/Product/GetAll'),
    sendConfirmationCode: useRequestCenter('Account/SendConfirmationCode'),
    signUp: useRequestCenter('Account/SignUp'),
    registerMarketer: useRequestCenter('User/RegisterMarketer'),
    getAllStates: useRequestCenter('State/GetAll'),
    getAllCities: useRequestCenter('City/GetByStateID'),
    getUserByToken: useRequestCenter('User/GetById'),
    forgotPassword:useRequestCenter('Account/ForgotPassword'),
    getMenu: useRequestCenter( 'Message/GetMenu'),
    getConversation: useRequestCenter( 'Message/GetConversation'),
    readMessage: useRequestCenter( 'Message/ReadMessage'),
    // sendMessage: useRequestCenter( 'Message/SendMessage'),
    deliverMessage: useRequestCenter( 'Message/DeliverMessage'),
    getUserById:useRequestCenter('User/Get'),
    upSert:useRequestCenter('Company/UpSert'),
    updateCompanyByAdmin:useRequestCenter('Company/UpdateCompanyByAdmin'),
    createAddress:useRequestCenter('Company/CreateAddress'),
    updateAddress:useRequestCenter('Company/updateAddress'),
    deleteAddress:useRequestCenter('Company/deleteAddress'),
    createPersonnel:useRequestCenter('Company/AddUserByCustomerAdmin'),
    createUserByAdmin:useRequestCenter('User/CreateUserByAdmin'),
    changePassword:useRequestCenter('Account/ChangePassword'),
    updateUser:useRequestCenter('User/Update'),
    updateUserByAdmin:useRequestCenter('User/UpdateUserByAdmin'),
    getUserCompany:useRequestCenter('User/GetUserCompany'),
    getUserCompanyForAdmin:useRequestCenter('User/GetUserCompanyByUserId'),
    // getCompanyPersonnel:useRequestCenter('Company/GetAllCompanyPersonnel'),
    // getAllCompanyRequests:useRequestCenter('Request/GetAllCompanyRequest'),
    getAllUserRequests:useRequestCenter('Request/GetAllUserRequest'),
    getTypesOfService:useRequestCenter('Request/GetTypeOfServices'),
    getRequestTypes:useRequestCenter('Request/GetRequestTypes'),
    getAllTestQuestions:useRequestCenter('Test/GetAllTestQuestion'),
    createTestQuestion:useRequestCenter('Test/CreateTestQuestion'),
    deleteTestQuestion:useRequestCenter('Test/DeleteTestQuestion'),

}
